services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    # We'll mount the custom nginx.conf we placed in diplomovka/nginx.conf
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always
    networks:
      - app-network
    volumes:
      - ./backend/storage:/var/www/html/storage

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: postgres-database
      POSTGRES_USER: postgres-username
      POSTGRES_PASSWORD: postgres-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
