services:
  app:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - docker-network
    ports:
      - "9000:9000"
    volumes:
      - ./backend/:/var/www/html/
    depends_on:
      - db

#  test_runner:
#    build:
#      context: .
#      dockerfile: testrunner/Dockerfile
#    volumes:
#      - ./tests:/var/www/html/storage/private/tests


  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "433:433"
    volumes:
      - ./diplomovka:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-network
    depends_on:
      - app

  db:
    image: bitnami/postgresql:16.3.0
    platform: linux/amd64
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    networks:
      - docker-network


volumes:
  db-data:

networks:
  docker-network:
    driver: bridge
